language: ruby

services:
  - postgresql

before_script:
  - psql -U postgres -c 'CREATE DATABASE chitter_test;
  \c chitter
  CREATE TABLE users (id SERIAL PRIMARY KEY, 
                      username VARCHAR(60), 
                      email VARCHAR(60), 
                      password VARCHAR(60), 
                      full_name VARCHAR(60));
  CREATE TABLE peeps (id SERIAL PRIMARY KEY, 
                      body VARCHAR(280), 
                      time_date_form TIMESTAMPTZ);
  CREATE TABLE feed (id SERIAL PRIMARY KEY, 
                    user_id INTEGER, 
                    peep_id INTEGER,
                    FOREIGN KEY (user_id) REFERENCES users(id),
                    FOREIGN KEY (peep_id) REFERENCES peeps(id));'

script:
  - bundle exec rspec
 