env:
  global:
    - CC_TEST_REPORTER_ID=e8cdefa65969433b034568fbc7186895620309a9b34a607bf4f13d7dcf0f929d

language: ruby

services:
  - postgresql

before_script:
  - psql -c 'CREATE DATABASE chitter_test;' -U postgres
  - psql -d chitter_test -f db/migrations/01_create_users_table.sql
  - psql -d chitter_test -f db/migrations/02_create_peeps_table.sql
  - psql -d chitter_test -f db/migrations/03_create_feed_table.sql
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - bundle exec rspec
 
after_script:
  - ./cc-test-reporter after-build -t lcov --exit-code $TRAVIS_TEST_RESULT