# env:
#   global:
#     - CC_TEST_REPORTER_ID=f77449bd6fe9dcbc7c9bb5206294e21d5d222148764e141a93801a9d3d579ea0

language: ruby
rvm: 
  - 2.5.0

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - psql -c 'CREATE DATABASE chitter_test;' -U postgres
  - psql -d chitter_test -f db/migrations/01_create_users_table.sql
  - psql -d chitter_test -f db/migrations/02_create_peeps_table.sql
  - psql -d chitter_test -f db/migrations/03_create_feed_table.sql
  - bundle exec rspec
 
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT -d

services:
  - postgresql